# .github/workflows/sync.yml (Your reusable workflow)
name: 'Create sync PR'

on:
    workflow_call:
        inputs:
            sync_branch:
                description: 'Branch to sync with'
                required: true
                type: string
            pr_title:
                description: 'Title for the PR'
                required: true
                type: string
                default: 'Sync with main branch'
            pr_body:
                description: 'Body for the PR'
                required: false
                type: string
                default: 'This PR syncs the current branch with the main branch.'
            runner:
                description: 'Runner to use for the workflow'
                required: false
                type: string
                default: '["ubuntu-latest"]'
            target_repo_name: # NEW INPUT: The name of the repository to perform the sync on
                description: 'Name of the repository to sync'
                required: true
                type: string
        secrets:
            GH_PAT:
                required: true
        outputs:
            pr_number:
                description: 'Number of the created PR'
                value: ${{ jobs.sync.outputs.pr_number }}
            pr_url:
                description: 'URL of the created PR'
                value: ${{ jobs.sync.outputs.pr_url }}
            has_conflicts:
                description: 'Indicates if there are merge conflicts'
                value: ${{ jobs.sync.outputs.has_conflicts }}
jobs:
    sync:
        runs-on: ${{ fromJson(inputs.runner) }}
        outputs:
            pr_number: ${{ steps.create_pr.outputs.pr_number }}
            pr_url: ${{ steps.create_pr.outputs.pr_url }}
            has_conflicts: ${{ steps.merge_main.outputs.has_conflicts }}
        steps:
            - name: Checkout target repository
              uses: actions/checkout@v4
              with:
                repository: ${{ github.repository_owner }}/${{ inputs.target_repo_name }} # Use the passed repo name
                token: ${{ secrets.GH_PAT }}
                fetch-depth: 0 # Ensure full history for merge operations
                path: ./target-repo # Checkout into a specific directory

            - name: Validate required branches exist (via GitHub API)
              id: validate_branches
              uses: actions/github-script@v6
              with:
                script: |
                  const owner = context.repo.owner; // Owner of the current repo (where workflow lives)
                  const repo = '${{ inputs.target_repo_name }}'; // The target repo name from input

                  console.log(`Checking branches in repository: ${owner}/${repo}`);

                  try {
                    await github.rest.repos.getBranch({
                      owner: owner,
                      repo: repo,
                      branch: 'main'
                    });
                    console.log("Branch 'main' exists in the target repository.");
                  } catch (error) {
                    core.setFailed(`Error: The 'main' branch does not exist in the target repository (${owner}/${repo}). Please check the branch name or create it.`);
                  }
                  try {
                    await github.rest.repos.getBranch({
                      owner: owner,
                      repo: repo,
                      branch: 'yupdev'
                    });
                    console.log("Branch 'yupdev' exists in the target repository.");
                  } catch (error) {
                    core.setFailed(`Error: The 'yupdev' branch does not exist in the target repository (${owner}/${repo}). Please check the branch name or create it.`);
                  }
              env:
                GITHUB_TOKEN: ${{ secrets.GH_PAT }} # Use the PAT for API calls

            - name: Setup Git and perform merge operations
              shell: bash
              working-directory: ./target-repo # All commands run inside this directory
              run: |
                git config user.name "GitHub Actions"
                git config user.email "actions@github.com"
                
                # Fetch main and yupdev explicitly within the target repo's context
                git fetch origin main
                git fetch origin yupdev
                
                # Create or checkout the sync branch
                if git show-ref --verify --quiet refs/heads/${{ inputs.sync_branch }}; then
                    echo "Sync branch '${{ inputs.sync_branch }}' already exists locally. Checking it out and resetting."
                    git checkout ${{ inputs.sync_branch }}
                else
                    echo "Sync branch '${{ inputs.sync_branch }}' does not exist. Creating it from origin/yupdev."
                    git checkout -b ${{ inputs.sync_branch }} origin/yupdev
                fi
                # Always reset the branch to origin/yupdev to ensure a clean state
                git reset --hard origin/yupdev

                # Merge the source's main branch into the sync branch
                if git merge origin/main --no-edit --no-ff; then
                    echo "has_conflicts=false" >> $GITHUB_OUTPUT
                else
                    echo "has_conflicts=true" >> $GITHUB_OUTPUT
                    echo "Merge conflicts detected."
                    git status
                    exit 1
                fi
            
            - name: Check for new commits
              id: check_changes
              shell: bash
              working-directory: ./target-repo # All commands run inside this directory
              run: |
                # Compare the current HEAD with the state of the yupdev branch in the target repo
                # This checks if the merge operation actually introduced new commits
                if [ "$(git rev-parse HEAD)" = "$(git rev-parse origin/yupdev)" ]; then
                    echo "has_changes=false" >> $GITHUB_OUTPUT
                    echo "No new commits to sync."
                else
                    echo "has_changes=true" >> $GITHUB_OUTPUT
                fi

            - name: Push sync branch
              if: steps.check_changes.outputs.has_changes == 'true'
              shell: bash
              working-directory: ./target-repo # All commands run inside this directory
              run: |
                git push origin ${{ inputs.sync_branch }} --force
            
            - name: Create pull request
              id: create_pr
              if: steps.check_changes.outputs.has_changes == 'true'
              shell: bash
              working-directory: ./target-repo # All commands run inside this directory
              env:
                GITHUB_TOKEN: ${{ secrets.GH_PAT }}
              run: |
                PR_URL=$(gh pr create \
                    --base yupdev \
                    --title "${{ inputs.pr_title }}" \
                    --body "${{ inputs.pr_body }}" \
                    --head ${{ inputs.sync_branch }})
                PR_NUMBER=$(echo $PR_URL | grep -oE '[0-9]+$')
                echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
                echo "pr_url=$PR_URL" >> $GITHUB_OUTPUT